*** Variables ***
${Global_login_schema_pos}    ${CURDIR}\\..\\Schemas\\Login_Pos.json
${Global_login_schema_neg}    ${CURDIR}\\..\\Schemas\\Login_Neg.json
${Global_login_schema_UserID}    ${CURDIR}\\..\\Schemas\\Get_UserID.json
${Global_login_schema_AllUsers}    ${CURDIR}\\..\\Schemas\\Get_AllUsers.json
${Global_login_schema_CreateUser}    ${CURDIR}\\..\\Schemas\\Create_User.json
${Global_login_schema_NegCreateUser}    ${CURDIR}\\..\\Schemas\\Neg_Create_User.json
${Global_deletion_schema}    ${CURDIR}\\..\\Schemas\\User_deletion.json
